/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

	// But you can create a sidebar manually

	// tutorialSidebar: [
	// 	"intro",
	// 	{
	// 		type: "category",
	// 		label: "Tutorial",
	// 		items: ["tutorial-basics/create-a-document"],
	// 	},

	// ],

	// tutorialSidebar: [
	// 	"appSeed",
	// 	"support",
	// 	"app-generator",
	// 	{
	// 		type: "category",
	// 		label: "BOILERPLATE CODE",
	// 		collapsed: true,
	// 		items: [
	// 			{
	// 				type: "category",
	// 				label: "API Servers",
	// 				collapsed: false,
	// 				items: [
	// 					"boilerplate-code/api-server/api-unified-definition",
	// 					// "API Server Django",
	// 					//  "API Server Flask",
	// 					//  "API Server Node JS"
	// 				],
	// 			},
	// 		],
	// 	},

	// 	// "Boilerplate Django Dashboard",
	// ],
};

module.exports = sidebars;
